name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "petrobubka-flask-application-packages"
  EB_APPLICATION_NAME       : "FlaskAPP"
  EB_ENVIRONMENT_NAME       : "MFlaskAPP-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-north-1"


on: 
  push:
    branches:
      - master
      
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
    
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    
